use crate::model::DeploymentModel;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AzureProvisioningPlan {
    pub resource_group: String,
    pub cluster_name: String,
    pub steps: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GreenfieldNames {
    pub env: String,
    pub location: String,
    pub resource_group: String,
    pub aks_cluster: String,
    pub acr_name: String,
    pub key_vault_name: String,
    pub storage_account_name: String,
    pub search_service_name: String,
    pub openai_account_name: String,
}

pub trait AzureProvisioner {
    fn plan(&self, model: &DeploymentModel) -> AzureProvisioningPlan;
}

#[derive(Debug, Default)]
pub struct DryRunAzureProvisioner;

impl AzureProvisioner for DryRunAzureProvisioner {
    fn plan(&self, model: &DeploymentModel) -> AzureProvisioningPlan {
        AzureProvisioningPlan {
            resource_group: model.azure.resource_group.clone(),
            cluster_name: model.azure.aks_cluster.clone(),
            steps: vec![
                format!(
                    "enforce isolation policy '{}' with name prefix '{}'",
                    model.isolation.mode, model.isolation.name_prefix
                ),
                format!(
                    "create a brand-new resource group '{}' and fail if it already exists",
                    model.azure.resource_group
                ),
                "create new network, AKS, ACR, identities, Key Vault, storage, AI, and search resources inside the new resource group only".to_string(),
                "reject reuse of existing Azure resources, clusters, namespaces, hostnames, identities, or resource groups".to_string(),
                format!(
                    "deny legacy/current names: {}",
                    model.isolation.denied_legacy_names.join(", ")
                ),
                "render Kubernetes manifests for review against the new namespace only".to_string(),
                "stop before any Azure, kubectl, Docker, or Terraform write operation".to_string(),
            ],
        }
    }
}

impl GreenfieldNames {
    pub fn new(env: &str, location: &str) -> Result<Self, String> {
        validate_env(env)?;
        let compact_env = env.replace('-', "");
        let resource_group = format!("rg-sageinfra-new-{env}");
        let aks_cluster = format!("aks-sageinfra-new-{env}");
        let acr_name = format!("sageinfranew{compact_env}");
        let key_vault_name = format!("kv-sageinfra-new-{env}");
        let storage_account_name = format!("stsageinfranew{compact_env}");
        let search_service_name = format!("srch-sageinfra-new-{env}");
        let openai_account_name = format!("oai-sageinfra-new-{env}");

        validate_len("ACR name", &acr_name, 5, 50)?;
        validate_len("Key Vault name", &key_vault_name, 3, 24)?;
        validate_len("storage account name", &storage_account_name, 3, 24)?;
        validate_len("Search service name", &search_service_name, 2, 60)?;
        validate_len("OpenAI account name", &openai_account_name, 2, 64)?;

        Ok(Self {
            env: env.to_string(),
            location: location.to_string(),
            resource_group,
            aks_cluster,
            acr_name,
            key_vault_name,
            storage_account_name,
            search_service_name,
            openai_account_name,
        })
    }
}

pub fn render_greenfield_provision_script(
    model: &DeploymentModel,
    names: &GreenfieldNames,
) -> String {
    let denied = model.isolation.denied_legacy_names.join(" ");
    format!(
        r#"#!/usr/bin/env bash
set -euo pipefail

# Generated by sageinfra. Greenfield-only: do not edit this into an existing-stack deploy.
ENV_NAME='{env}'
LOCATION='{location}'
RG='{rg}'
AKS='{aks}'
ACR='{acr}'
KEYVAULT='{kv}'
STORAGE='{storage}'
SEARCH='{search}'
OPENAI='{openai}'
NAMESPACE='{namespace}'
DENIED_LEGACY_NAMES='{denied}'

echo 'SageInfra greenfield preflight'
az account show --query '{{subscription:id, tenant:tenantId, user:user.name}}' -o json

if [ "$(az group exists --name "$RG")" != 'false' ]; then
  echo "Refusing to continue: resource group already exists: $RG" >&2
  exit 20
fi

if [ "$(az aks list --query "[?name=='$AKS'] | length(@)" -o tsv)" != '0' ]; then
  echo "Refusing to continue: AKS cluster name already exists in this subscription: $AKS" >&2
  exit 21
fi

if [ "$(az acr check-name --name "$ACR" --query nameAvailable -o tsv)" != 'true' ]; then
  echo "Refusing to continue: ACR name is unavailable: $ACR" >&2
  exit 22
fi

if [ "$(az keyvault check-name --name "$KEYVAULT" --query nameAvailable -o tsv)" != 'true' ]; then
  echo "Refusing to continue: Key Vault name is unavailable: $KEYVAULT" >&2
  exit 23
fi

if [ "$(az storage account check-name --name "$STORAGE" --query nameAvailable -o tsv)" != 'true' ]; then
  echo "Refusing to continue: storage account name is unavailable: $STORAGE" >&2
  exit 24
fi

if [ "$(az resource list --resource-type "Microsoft.Search/searchServices" --query "[?name=='$SEARCH'] | length(@)" -o tsv)" != '0' ]; then
  echo "Refusing to continue: Search service name already exists in this subscription: $SEARCH" >&2
  exit 25
fi

if [ "$(az resource list --resource-type "Microsoft.CognitiveServices/accounts" --query "[?name=='$OPENAI'] | length(@)" -o tsv)" != '0' ]; then
  echo "Refusing to continue: Azure AI/OpenAI account name already exists in this subscription: $OPENAI" >&2
  exit 26
fi

for denied in $DENIED_LEGACY_NAMES; do
  case "$RG $AKS $ACR $KEYVAULT $STORAGE $SEARCH $OPENAI $NAMESPACE" in
    *"$denied"*)
      echo "Refusing to continue: planned names contain denied legacy/current name: $denied" >&2
      exit 27
      ;;
  esac
done

echo 'Preflight passed. Creating brand-new isolated Azure resources.'
az group create \
  --name "$RG" \
  --location "$LOCATION" \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az acr create \
  --resource-group "$RG" \
  --name "$ACR" \
  --sku Basic \
  --admin-enabled false \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az keyvault create \
  --resource-group "$RG" \
  --name "$KEYVAULT" \
  --location "$LOCATION" \
  --enable-rbac-authorization true \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az storage account create \
  --resource-group "$RG" \
  --name "$STORAGE" \
  --location "$LOCATION" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --allow-blob-public-access false \
  --min-tls-version TLS1_2 \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az search service create \
  --resource-group "$RG" \
  --name "$SEARCH" \
  --location "$LOCATION" \
  --sku basic \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az cognitiveservices account create \
  --resource-group "$RG" \
  --name "$OPENAI" \
  --location "$LOCATION" \
  --kind OpenAI \
  --sku S0 \
  --custom-domain "$OPENAI" \
  --yes \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

az aks create \
  --resource-group "$RG" \
  --name "$AKS" \
  --location "$LOCATION" \
  --enable-managed-identity \
  --node-count 1 \
  --node-vm-size Standard_B2s \
  --attach-acr "$ACR" \
  --generate-ssh-keys \
  --enable-oidc-issuer \
  --enable-workload-identity \
  --tags managed-by=sageinfra isolation=greenfield env="$ENV_NAME"

echo 'Greenfield Azure infrastructure created. Kubernetes manifest application remains a separate reviewed step.'
"#,
        env = names.env,
        location = names.location,
        rg = names.resource_group,
        aks = names.aks_cluster,
        acr = names.acr_name,
        kv = names.key_vault_name,
        storage = names.storage_account_name,
        search = names.search_service_name,
        openai = names.openai_account_name,
        namespace = model.namespace,
        denied = denied,
    )
}

fn validate_env(env: &str) -> Result<(), String> {
    if env.is_empty() {
        return Err("--env must not be empty".to_string());
    }
    if !env
        .chars()
        .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-')
    {
        return Err("--env may only contain lowercase letters, digits, and hyphens".to_string());
    }
    if env.starts_with('-') || env.ends_with('-') {
        return Err("--env must not start or end with a hyphen".to_string());
    }
    Ok(())
}

fn validate_len(label: &str, value: &str, min: usize, max: usize) -> Result<(), String> {
    if value.len() < min || value.len() > max {
        return Err(format!(
            "{label} '{value}' must be between {min} and {max} characters"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_names_are_greenfield_and_azure_safe() {
        let names = GreenfieldNames::new("dev01", "eastus2").unwrap();

        assert_eq!(names.resource_group, "rg-sageinfra-new-dev01");
        assert_eq!(names.aks_cluster, "aks-sageinfra-new-dev01");
        assert_eq!(names.acr_name, "sageinfranewdev01");
        assert_eq!(names.key_vault_name, "kv-sageinfra-new-dev01");
        assert_eq!(names.storage_account_name, "stsageinfranewdev01");
    }

    #[test]
    fn script_fails_closed_before_create_commands() {
        let model = DeploymentModel::default_sageinsure();
        let names = GreenfieldNames::new("dev01", "eastus2").unwrap();
        let script = render_greenfield_provision_script(&model, &names);

        assert!(script.contains("Refusing to continue: resource group already exists"));
        assert!(script.contains("az group create"));
        assert!(script.contains("az aks create"));
        assert!(script.contains("--attach-acr \"$ACR\""));
        assert!(!script.contains("sageinsure-workload-identity"));
    }
}
