apiVersion: v1
kind: Service
metadata:
  name: {{ include "sageinsure-frontend.fullname" . }}
  labels:
    {{- include "sageinsure-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.monitoring.enabled }}
    - port: {{ .Values.monitoring.port }}
      targetPort: {{ .Values.monitoring.port }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "sageinsure-frontend.selectorLabels" . | nindent 4 }}