{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "sageinsure-worker.fullname" . }}-secrets
  labels:
    {{- include "sageinsure-worker.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ include "sageinsure-worker.fullname" . }}-secrets
    type: Opaque
    data:
    {{- range .Values.keyVault.secrets }}
    - objectName: {{ .name }}
      key: {{ .name }}
    {{- end }}
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "{{ .Values.serviceAccount.annotations.azure.workload.identity/client-id }}"
    keyvaultName: "{{ .Values.keyVault.name }}"
    cloudName: ""
    objects: |
      array:
        {{- range .Values.keyVault.secrets }}
        - |
          objectName: {{ .key }}
          objectType: secret
          objectAlias: {{ .name }}
        {{- end }}
    tenantId: "e9394f90-446d-41dd-8c8c-98ac08c5f090"
{{- end }}